# Generated by Django 4.2.5 on 2023-09-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
